spring:
  profiles:
    active: dev
  application:
    name: vgq
  mvc:
    throw-exception-if-no-handler-found: false
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      add-mappings: false
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: /game

logging:
  config: classpath:logback-spring.xml
export:
  password: b123456Y@
  sheet: data
  frequent-msg: "The operation is too frequent, please try again later!"