//package github.polarisink.vgq.domain.answer;
//
//import lombok.Getter;
//import lombok.RequiredArgsConstructor;
//
//import java.util.HashMap;
//import java.util.Map;
//
///**
// * @author lqsgo
// */
//@Getter
//@RequiredArgsConstructor
//public enum CountryEnum {
//
//  AD("安道尔", "Andorra", "AND"),
//  AE("阿拉伯联合酋长国", "United Arab Emirates", "ARE"),
//  AF("阿富汗", "Afghanistan", "AFG"),
//  AG("安提瓜和巴布达", "Antigua and Barbuda", "ATG"),
//  AI("安圭拉", "Anguilla", "AIA"),
//  AL("阿尔巴尼亚", "Albania", "ALB"),
//  AM("亚美尼亚", "Armenia", "ARM"),
//  AN("荷属安的列斯群岛", "The Netherlands Antilles", "ANT"),
//  AO("安哥拉", "Angola", "AGO"),
//  AQ("南极洲", "Antarctica", "ATA"),
//  AR("阿根廷", "Argentina", "ARG"),
//  AS("东萨摩亚", "American Samoa", "ASM"),
//  AT("奥地利", "Austria", "AUT"),
//  AU("澳大利亚", "Australia", "AUS"),
//  AW("阿鲁巴", "Aruba", "ABW"),
//  AX("奥兰群岛", "Aland Islands", "ALA"),
//  AZ("阿塞拜疆", "Azerbaijan", "AZE"),
//  BA("波斯尼亚和黑山共和国", "Bosnia and Montenegro", "BIH"),
//  BB("巴巴多斯", "Barbados", "BRB"),
//  BD("孟加拉", "Bangladesh", "BGD"),
//  BE("比利时", "Belgium", "BEL"),
//  BF("布基纳法索", "Burkina Faso", "BFA"),
//  BG("保加利亚", "Bulgaria", "BGR"),
//  BH("巴林", "Bahrain", "BHR"),
//  BI("布隆迪", "Burundi", "BDI"),
//  BJ("贝宁", "Benin", "BEN"),
//  BL("圣巴泰勒米岛", "St. Barthelemy", "BLM"),
//  BM("百慕大", "Bermuda", "BMU"),
//  BN("文莱", "Brunei", "BRN"),
//  BO("玻利维亚", "Bolivia", "BOL"),
//  BQ("博奈尔岛, 圣尤斯特歇斯岛和萨巴岛", "Bonaire, Saint Eustatius and Saba", "BES"),
//  BR("巴西", "Brazil", "BRA"),
//  //TODO 继续
//  BS("巴哈马", "Bahamas", "BHS"),
//  BT("不丹", "Bhutan", "BTN"),
//  BV("布韦岛", "Bouvet Cay", "BVT"),
//  BW("博茨瓦纳", "Botswana", "BWA"),
//  BY("白俄罗斯", "Belarus", "BLR"),
//  BZ("伯里兹", "Buryze", "BLZ"),
//  CA("加拿大", "Canada", "CAN"),
//  CC("科库斯群岛", "The Cocus Islands", "CCK"),
//  CD("刚果民主共和国", "Democratic Republic of the Congo", "COD"),
//  CF("中非共和国", "Central African Republic", "CAF"),
//  CG("刚果", "Congo", "COG"),
//  CH("瑞士", "Switzerland", "CHE"),
//  CI("象牙海岸", "Ivory Coast", "CIV"),
//  CK("库克群岛", "Cook Islands", "COK"),
//  CL("智利", "Chile", "CHL"),
//  CM("喀麦隆", "Cameroon", "CMR"),
//  CN("中国", "China", "CHN"),
//  CO("哥伦比亚", "Colombia", "COL"),
//  CR("哥斯达黎加", "Costa Rica", "CRI"),
//  CS("塞尔维亚及黑山", "Belgium", "Serbia and Montenegro"),
//  CU("古巴", "Belgium", "CUB"),
//  CV("佛得角", "Belgium", "CPV"),
//  CW("库拉索岛", "Belgium", "CUW"),
//  CX("圣诞岛", "Belgium", "CXR"),
//  CY("塞浦路斯", "Belgium", "CYP"),
//  CZ("捷克共和国", "Belgium", "CZE"),
//  DE("德国", "Belgium", "DEU"),
//  DJ("吉布提", "Belgium", "DJI"),
//  DK("丹麦", "Belgium", "DNK"),
//  DM("多米尼加联邦", "Belgium", "DMA"),
//  DO("多米尼加共和国", "Belgium", "DOM"),
//  DZ("阿尔及利亚", "Belgium", "DZA"),
//  EC("厄瓜多尔", "Belgium", "ECU"),
//  EE("爱沙尼亚", "Belgium", "EST"),
//  EG("埃及", "Belgium", "EGY"),
//  EH("西撒哈拉", "Belgium", "ESH"),
//  ER("厄里特尼亚", "Belgium", "ERI"),
//  ES("西班牙", "Belgium", "ESP"),
//  ET("埃塞俄比亚", "Belgium", "ETH"),
//  FI("芬兰", "Belgium", "FIN"),
//  FJ("斐济", "Belgium", "FJI"),
//  FK("富克兰群岛", "Belgium", "FLK"),
//  FM("密克罗尼西亚", "Belgium", "FSM"),
//  FO("法罗群岛", "Belgium", "FRO"),
//  FR("法国", "Belgium", "FRA"),
//  GA("加蓬", "Belgium", "GAB"),
//  GB("英国", "Belgium", "GBR"),
//  GD("格林纳达", "Belgium", "GRD"),
//  GE("格鲁吉亚", "Belgium", "GEO"),
//  GF("法属圭亚那", "Belgium", "GUF"),
//  GG("格恩西岛", "Belgium", "GGY"),
//  GH("加纳", "Belgium", "GHA"),
//  GI("直布罗陀", "Belgium", "GIB"),
//  GL("格陵兰", "Belgium", "GRL"),
//  GM("冈比亚", "Belgium", "GMB"),
//  GN("几内亚", "Belgium", "GIN"),
//  GP("瓜德罗普岛", "Belgium", "GLP"),
//  GQ("赤道几内亚", "Belgium", "GNQ"),
//  GR("希腊", "Belgium", "GRC"),
//  GS("南乔治亚岛和南桑德韦奇岛", "Belgium", "SGS"),
//  GT("危地马拉", "Belgium", "GTM"),
//  GU("关岛", "Belgium", "GUM"),
//  GW("几内亚比绍共和国", "Belgium", "GNB"),
//  GY("圭亚那", "Belgium", "GUY"),
//  HK("香港", "Belgium", "HKG"),
//  HM("赫德和麦克唐纳群岛", "Belgium", "HMD"),
//  HN("洪都拉斯", "Belgium", "HND"),
//  HR("克罗地亚", "Belgium", "HRV"),
//  HT("海地", "Belgium", "HTI"),
//  HU("匈牙利", "Belgium", "HUN"),
//  ID("印度尼西亚", "Belgium", "IDN"),
//  IE("爱尔兰", "Belgium", "IRL"),
//  IL("以色列", "Belgium", "ISR"),
//  IM("曼岛", "Belgium", "IMN"),
//  IN("印度", "Belgium", "IND"),
//  IO("英属印度洋领地", "Belgium", "IOT"),
//  IQ("伊拉克", "Belgium", "IRQ"),
//  IR("伊朗", "Belgium", "IRN"),
//  IS("冰岛", "Belgium", "ISL"),
//  IT("意大利", "Belgium", "ITA"),
//  JE("泽西岛", "Belgium", "JEY"),
//  JM("牙买加", "Belgium", "JAM"),
//  JO("约旦", "Belgium", "JOR"),
//  JP("日本", "Belgium", "JPN"),
//  KE("肯尼亚", "Belgium", "KEN"),
//  KG("吉尔吉克斯坦", "Belgium", "KGZ"),
//  KH("柬埔寨", "Belgium", "KHM"),
//  KI("基里巴斯", "Belgium", "KIR"),
//  KM("科摩罗", "Belgium", "COM"),
//  KN("圣基茨和尼维斯", "Belgium", "KNA"),
//  KP("朝鲜", "Belgium", "PRK"),
//  KR("韩国", "Belgium", "KOR"),
//  KW("科威特", "Belgium", "KWT"),
//  KY("开曼群岛", "Belgium", "CYM"),
//  KZ("哈萨克斯坦", "Belgium", "KAZ"),
//  LA("老挝", "Belgium", "LAO"),
//  LB("黎巴嫩", "Belgium", "LBN"),
//  LC("圣卢西亚", "Belgium", "LCA"),
//  LI("列支敦士登", "Belgium", "LIE"),
//  LK("斯里兰卡", "Belgium", "LKA"),
//  LR("利比里亚", "Belgium", "LBR"),
//  LS("莱索托", "Belgium", "LSO"),
//  LT("立陶宛", "Belgium", "LTU"),
//  LU("卢森堡", "Belgium", "LUX"),
//  LV("拉脱维亚", "Belgium", "LVA"),
//  LY("利比亚", "Belgium", "LBY"),
//  MA("摩洛哥", "Belgium", "MAR"),
//  MC("摩纳哥", "Belgium", "MCO"),
//  MD("摩尔多瓦", "Belgium", "MDA"),
//  ME("黑山", "Belgium", "MNE"),
//  MF("圣马丁", "Belgium", "MAF"),
//  MG("马达加斯加", "Belgium", "MDG"),
//  MH("马绍尔群岛", "Belgium", "MHL"),
//  MK("马其顿王国", "Belgium", "MKD"),
//  ML("马里", "Belgium", "MLI"),
//  MM("缅甸", "Belgium", "MMR"),
//  MN("蒙古", "Belgium", "MNG"),
//  MO("澳门特区", "Belgium", "MAC"),
//  MP("美属北马里亚纳群岛", "Belgium", "MNP"),
//  MQ("马提尼克岛", "Belgium", "MTQ"),
//  MR("毛里塔尼亚", "Belgium", "MRT"),
//  MS("蒙特塞拉群岛", "Belgium", "MSR"),
//  MT("马耳他", "Belgium", "MLT"),
//  MU("毛里求斯", "Belgium", "MUS"),
//  MV("马尔代夫", "Belgium", "MDV"),
//  MW("马拉维", "Belgium", "MWI"),
//  MX("墨西哥", "Belgium", "MEX"),
//  MY("马来西亚", "Belgium", "MYS"),
//  MZ("莫桑比克", "Belgium", "MOZ"),
//  NA("纳米比亚", "Belgium", "NAM"),
//  NC("新克里多尼亚群岛", "Belgium", "NCL"),
//  NE("尼日尔", "Belgium", "NER"),
//  NF("诺福克岛", "Belgium", "NFK"),
//  NG("尼日利亚", "Belgium", "NGA"),
//  NI("尼加拉瓜", "Belgium", "NIC"),
//  NL("荷兰", "Belgium", "NLD"),
//  NO("挪威", "Belgium", "NOR"),
//  NP("尼泊尔", "Belgium", "NPL"),
//  NR("瑙鲁", "Belgium", "NRU"),
//  NU("纽埃岛", "Belgium", "NIU"),
//  NZ("新西兰", "Belgium", "NZL"),
//  OM("阿曼", "Belgium", "OMN"),
//  PA("巴拿马", "Belgium", "PAN"),
//  PE("秘鲁", "Belgium", "PER"),
//  PF("法属玻利尼西亚", "Belgium", "PYF"),
//  PG("巴布亚新几内亚", "Belgium", "PNG"),
//  PH("菲律宾", "Belgium", "PHL"),
//  PK("巴基斯坦", "Belgium", "PAK"),
//  PL("波兰", "Belgium", "POL"),
//  PM("圣皮埃尔和密克隆群岛", "Belgium", "SPM"),
//  PN("皮特克恩岛", "Belgium", "PCN"),
//  PR("波多黎哥", "Belgium", "PRI"),
//  PS("巴勒斯坦", "Belgium", "PSE"),
//  PT("葡萄牙", "Belgium", "PRT"),
//  PW("帕劳", "Belgium", "PLW"),
//  PY("巴拉圭", "Belgium", "PRY"),
//  QA("卡塔尔", "Belgium", "QAT"),
//  RE("留尼汪岛", "Belgium", "REU"),
//  RO("罗马尼亚", "Belgium", "ROU"),
//  RS("塞尔维亚", "Belgium", "SRB"),
//  RU("俄罗斯", "Belgium", "RUS"),
//  RW("卢旺达", "Belgium", "RWA"),
//  SA("沙特阿拉伯", "Belgium", "SAU"),
//  SB("所罗门群岛", "Belgium", "SLB"),
//  SC("塞舌尔群岛", "Belgium", "SYC"),
//  SD("苏丹", "Belgium", "SDN"),
//  SE("瑞典", "Belgium", "SWE"),
//  SG("新加坡", "Belgium", "SGP"),
//  SH("圣赫勒拿岛", "Belgium", "SHN"),
//  SI("斯洛文尼亚", "Belgium", "SVN"),
//  SJ("斯瓦尔巴特和扬马延岛", "Belgium", "SJM"),
//  SK("斯洛伐克", "Belgium", "SVK"),
//  SL("塞拉里昂", "Belgium", "SLE"),
//  SM("圣马力诺", "Belgium", "SMR"),
//  SN("塞内加尔", "Belgium", "SEN"),
//  SO("索马里", "Belgium", "SOM"),
//  SR("苏里南", "Belgium", "SUR"),
//  SS("南苏丹", "Belgium", "SSD"),
//  ST("圣多美和普林西比", "Belgium", "STP"),
//  SV("萨尔瓦多", "Belgium", "SLV"),
//  SX("荷属圣马丁岛", "Belgium", "SXM"),
//  SY("叙利亚", "Belgium", "SYR"),
//  SZ("斯威士兰", "Belgium", "SWZ"),
//  TC("特克斯群岛和凯科斯群岛", "Belgium", "TCA"),
//  TD("乍得", "Belgium", "TCD"),
//  TF("法属南特立尼达", "Belgium", "ATF"),
//  TG("多哥", "Belgium", "TGO"),
//  TH("泰国", "Belgium", "THA"),
//  TJ("塔吉克斯坦", "Belgium", "TJK"),
//  TK("联合群岛", "Belgium", "TKL"),
//  TL("东帝汶", "Belgium", "TLS"),
//  TM("土库曼斯坦", "Belgium", "TKM"),
//  TN("突尼斯", "Belgium", "TUN"),
//  TO("汤加", "Belgium", "TON"),
//  TR("土耳其", "Belgium", "TUR"),
//  TT("特立尼达和多巴哥", "Belgium", "TTO"),
//  TV("图瓦卢", "Belgium", "TUV"),
//  TW("台湾地区", "Belgium", "TWN"),
//  TZ("坦桑尼亚", "Belgium", "TZA"),
//  UA("乌克兰", "Belgium", "UKR"),
//  UG("乌干达", "Belgium", "UGA"),
//  UM("美属小奥特兰群岛", "Belgium", "UMI"),
//  US("美国", "America", "USA"),
//  UY("乌拉圭", "Belgium", "URY"),
//  UZ("乌兹别克斯坦", "Belgium", "UZB"),
//  VA("梵蒂冈", "Vatican", "VAT"),
//  VC("圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", "VCT"),
//  VE("委内瑞拉", "Venezuela", "VEN"),
//  VG("英属维京群岛", "British Virgin Islands", "VGB"),
//  VI("美属维京群岛", "United States Virgin Islands", "VIR"),
//  VN("越南", "Vietnam", "VNM"),
//  VU("瓦努阿图", "Vanuatu", "VUT"),
//  WF("瓦利斯群岛和富图纳群岛", "Wallis Islands and Futuna Islands", "WLF"),
//  WS("东萨摩亚", "Eastern Samoa", "WSM"),
//  YE("也门", "Yemen", "YEM"),
//  YT("马约特岛", "The island of Mayotte", "MYT"),
//  ZA("南非", "South Africa", "ZAF"),
//  ZM("赞比亚", "Zambia", "ZMB"),
//  ZW("津巴布韦", "Zimbabwe", "ZWE");
//
//  public static CountryEnum getByCn(String country) {
//    return map.getOrDefault(country, US);
//  }
//
//  private static final Map<String, CountryEnum> map = new HashMap<>();
//
//  static {
//    for (CountryEnum c : values()) {
//      map.put(c.getCn(), c);
//    }
//  }
//
//  private final String cn;
//  private final String en;
//  private final String code;
//
//}